catcollector/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('', views.home, name='home'),
   path('about/', views.about, name='about'),
   path('cats/', views.cats_index, name='index'),
   path('cats/<int:cat_id>/', views.cats_detail, name='detail'),
   # new route used to show a form and create a cat
   path('cats/create/', views.CatCreate.as_view(), name='cats_create'),  
   path('cats/<int:pk>/update/', views.CatUpdate.as_view(), name='cats_update'),
   path('cats/<int:pk>/delete/', views.CatDelete.as_view(), name='cats_delete'),
   path('cats/<int:cat_id>/add_feeding/', views.add_feeding, name='add_feeding'),
]

main_app/models.py
from django.db import models
# Import the reverse function
from django.urls import reverse

# Create your models here.
# A tuple of 2-tuples
MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

class Cat(models.Model):
  name = models.CharField(max_length=100) 
  breed = models.CharField(max_length=100)
  description = models.TextField(max_length=250)
  age = models.IntegerField()

# new code below
  def __str__(self):
    return self.name    

# Add this method
  def get_absolute_url(self):
    return reverse('detail', kwargs={'cat_id': self.id})

# Add new Feeding model below Cat model
class Feeding(models.Model):
  date = models.DateField('feeding date')
  meal = models.CharField(
    max_length=1,
    # add the 'choices' field option
    choices=MEALS,
    # set the default value for meal to be 'B'
    default=MEALS[0][0]
  )

  # Create a cat_id FK
  cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

  def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
    return f"{self.get_meal_display()} on {self.date}"

  # change the default sort
  class Meta:
    ordering = ['-date']  

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
# Add the following import
from django.views.generic.edit import CreateView
from .models import Cat
# Import the FeedingForm
from .forms import FeedingForm
# Add UdpateView & DeleteView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

# Define the home view
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def cats_index(request):
  cats = Cat.objects.all()
  return render(request, 'cats/index.html', { 'cats': cats })
# The cats_detail function is using the getmethod to obtain the cat object by its id.
def cats_detail(request, cat_id):
  cat = Cat.objects.get(id=cat_id)
  # instantiate FeedingForm to be rendered in the template
  feeding_form = FeedingForm()
  return render(request, 'cats/detail.html', {
    # include the cat and feeding_form in the context
    'cat': cat, 'feeding_form': feeding_form
  })

def add_feeding(request, cat_id):
  # create the ModelForm using the data in request.POST
  form = FeedingForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_feeding = form.save(commit=False)
    new_feeding.cat_id = cat_id
    new_feeding.save()
  return redirect('detail', cat_id=cat_id)  

# The fieldsattribute is required and can be used to limit or change the ordering of the attributes from the Catmodel are generated in the ModelFormpassed to the template.
class CatCreate(CreateView):
  model = Cat
  fields = '__all__'  
  success_url = '/cats/'

class CatUpdate(UpdateView):
  model = Cat
  # Let's disallow the renaming of a cat by excluding the name field!
  fields = ['breed', 'description', 'age']

class CatDelete(DeleteView):
  model = Cat
  success_url = '/cats/'

main_app/templates/about.html
{% extends 'base.html'%} {% block content %}
<h1>About the cat collector</h1>

<hr/>

<p>Hire the Cat Colector</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"> 
    </script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
</head>

<body>

  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper #dce775 lime lighten-2">
        <ul>
          <li>
            <a href="/" class="left brand-logo">&nbsp;&nbsp;CatCollector</a>
          </li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'cats_create' %}">Add a Cat</a></li>
          <li><a href="{% url 'index' %}">View All My Cats</a></li>
        </ul>
      </div>
    </nav>
  </header>

  <main class="container">{% block content %} {% endblock %}</main>
  <footer class="page-footer #00e676 green accent-3">
    <div class="right">
      All Rights Reserved, &copy; 2022 Cat Collector &nbsp;
    </div>

  </footer>

</body>

</html>

main_app/templates/cats/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Cat Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ cat.name }}</span>
        <p>Breed: {{ cat.breed }}</p>
        <p>Description: {{ cat.description }}</p>
        {% if cat.age > 0 %}
        <p>Age: {{ cat.age }}</p>
        {% else %}
        <p>Age: Kitten</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'cats_update' cat.id %}">Edit</a>
        <a href="{% url 'cats_delete' cat.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_feeding' cat.id %}" method="post">
      {% csrf_token %} {{ feeding_form.as_p }}
      <input type="submit" class="btn" value="Add Feeding" />
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Meal</th>
        </tr>
      </thead>
      <tbody>
        {% for feeding in cat.feeding_set.all %}
        <tr>
          <td>{{feeding.date}}</td>
          <td>{{feeding.get_meal_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<script>
  var dateEl = document.getElementById("id_date");
  M.Datepicker.init(dateEl, {
    format: "yyyy-mm-dd",
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });
  // add additional JS to initialize select below
  var selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/cats/index.html
{% extends 'base.html' %} {% block content %}

<h1>Cat List</h1>

{% for cat in cats %}
<div class="card">
  <a href="{% url 'detail' cat.id %}"> 
   <div class="card-content">
    <span class="card-title">{{ cat.name }}</span>
    <p>Breed: {{ cat.breed }}</p>
    <p>Description: {{ cat.description }}</p>
    {% if cat.age > 0 %}
    <p>Age: {{ cat.age }}</p>
    {% else %}
    <p>Age: Kitten</p>
    {% endif %}
   </div>
  </a>
</div>
{% endfor %} {% endblock %}
<!-- endfor it's ending the for loop that we started at line 5 -->
<!-- line 8-10 are giving the cats a description using the data from vews -->
<!-- lin 6-7 is a buit in fuctionality from materialize to display cards  -->

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}

<h1>The Cat Collector</h1>

{% endblock %}

main_app/templates/main_app/cat_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Cat</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' cat.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/cat_form.html
{% extends 'base.html' %} {% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Cat</h1>
{% endif %}

<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}